# Generated by Django 3.1.7 on 2021-03-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='v4',
            field=models.CharField(default=0, max_length=255, verbose_name='Ответ 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='v5',
            field=models.CharField(default=1, max_length=255, verbose_name='Ответ 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='v6',
            field=models.CharField(default=1, max_length=255, verbose_name='Прав ответ'),
            preserve_default=False,
        ),
    ]
